Update to maintained Ruby version 2.7.6
dblock/iex-ruby-client pull request #114
Opened 2022-07-21 13:40 UTC by agrberg

2022-07-21 14:01 UTC, dblock requested changes
I don't see many benefits to making Ruby 2.7 the minimum. Maybe we can keep it at 2.4? 2.6? for now? Either way we need CI back to see what's possible #116

2022-07-21 18:55 UTC, agrberg commented on .rubocop.yml
> +Layout/LineLength:
I agree it's definitely gotten in my way before. The [reasoning in the style guide](https://rubystyle.guide/#max-line-length) and the [additional cops this helps with](https://docs.rubocop.org/rubocop/1.32/cops_layout.html#layoutlinelength) are convincing.

As it currently passes w/ this "fix" for lines ending in long comments, would it be acceptable to wait and see how long this is good enough for?

2022-07-21 19:00 UTC, agrberg commented on iex-ruby-client.gemspec
> +  s.required_ruby_version = '~> 2.7.6'
🤦 yes

2022-07-21 19:02 UTC, agrberg commented on iex-ruby-client.gemspec
> -  s.test_files = `git ls-files -- spec/*`.split("\n")
This field was deprecated from Gemspecs and Rubocop's [`Gemspec/DeprecatedAttributeAssignment`](https://docs.rubocop.org/rubocop/1.32/cops_gemspec.html#gemspecdeprecatedattributeassignment) got it

2022-07-21 19:03 UTC, agrberg commented on iex-ruby-client.gemspec
> -  s.add_development_dependency 'rubocop', '0.72.0'
Ah! Good point. Would it be better to lock it to the current latest version on this branch or let it float w/ [NewCops](https://github.com/dblock/iex-ruby-client/pull/114/commits/c90c558ad1b99181ba07c46030bd21d5327a2c04#diff-4f894049af3375c2bd4e608f546f8d4a0eed95464efcdea850993200db9fef5cR4) disabled? Failing CI would encourage any minor changes from Rubocop updates to be made as opposed to whole new cops.

2022-07-21 19:32 UTC, agrberg commented
> I don't see many benefits to making Ruby 2.7 the minimum. Maybe we can keep it at 2.4? 2.6? for now? Either way we need CI back to see what's possible #116

Good call regarding CI. It wasn't straightforward but it ended up being some minimal changes. I rebased this on #117 and split up the commits into an incredibly minimal [730dd06](https://github.com/dblock/iex-ruby-client/pull/114/commits/730dd062af7d73519a05ebc69b645411347dcb6f) to update the Ruby version.

Now [ec4020f](https://github.com/dblock/iex-ruby-client/pull/114/commits/ec4020f59c15899160dfac95fd0ef3e64bdd6c11) contains the safer changes and rubocop todo updates as well as additional current locks on the dev dependencies.

2022-07-22 00:16 UTC, dblock commented on .rubocop.yml
> +Layout/LineLength:
I'd prefer we disabled it instead of trying to be clever, but it's NBD.

2022-07-22 00:17 UTC, dblock commented on iex-ruby-client.gemspec
> -  s.add_development_dependency 'rubocop', '0.72.0'
I'd lock it with the most recent version possible and `NewCops: enable`, again just not trying to be too clever with it.

2022-07-22 00:18 UTC, dblock commented
Thanks so much for all of this! Let's get the CI to pass and cleanup the rest of the PRs.

2022-07-22 17:55 UTC, dblock commented
Rebase this one and let's re-review?

2022-07-22 18:08 UTC, agrberg commented on .rubocop.yml
> +Layout/LineLength:
Ultimately I didn't feel strongly enough and made the simpler change. I've definitely confused my future-self by being clever in the past 🙃

2022-07-22 18:09 UTC, agrberg commented
This one is ready but it still depends on the question of whether or not we want to restrict the library to only maintained versions of Ruby. The Rubocop updates are nice but hardly required.

2022-07-23 14:21 UTC, dblock commented
> This one is ready but it still depends on the question of whether or not we want to restrict the library to only maintained versions of Ruby. The Rubocop updates are nice but hardly required.

I think I'd rather not restrict the library unnecessarily, it's bound to make someone unhappy, I'm still on 2.6.x for example in at least one project that uses this. WDYT 

> FWIW It looks like the token I copied from your Slack client project [doesn't have write access](https://github.com/dblock/iex-ruby-client/runs/7473374501?check_suite_focus=true#step:4:11) to the project. While the output is not familiar, it appears to be successful and simply unable to state that it is successful via a PR comment.

I opened https://github.com/dblock/iex-ruby-client/issues/118, we can deal with it later. Danger isn't supposed to need write access, it just needs to be able to comment on the PRs, which is something any account (and therefore this super limited PAT) can do.

2022-07-23 22:07 UTC, agrberg commented
I agree. Going to close this. We'll revisit minimum Ruby version if there's a forward facing problem in the future like all the kwarg changes for Ruby 3.

2022-07-23 22:07 UTC, closed without merging